# Generated by Django 5.1.5 on 2025-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_remove_habit_high_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
    ]
