# Generated by Django 5.1.5 on 2025-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_habit_high_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
